### post user
POST http://localhost:5432/employee-api/employee
Content-Type: application/json

{
  "name":"mahesh",
  "email":"mahi@123",
  "mobile":9632014587,
  "designation":"student",
  "companyName":"AU"
}

###
GET http://localhost:5432/employee-api/employee

###
PUT http://localhost:5432/employee-api/employee/69ca2a1411d8313adf20d612
Content-Type: application/json

{
  "name":"mahesh",
  "email":"mahi@1234",
  "mobile":9632014587,
  "designation":"attender",
  "companyName":"Maharshi"
}

###Delete 
DELETE http://localhost:5432/employee-api/employee/69ca286573c70c8ae4d974db